[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LLMAccess = "1a9614b5-a00e-4537-a79a-85f37aa414d6"

[sources]
LLMAccess = {path = "/home/xing/code/ai/llmaccess.jl"}

[compat]
Documenter = "1"
